from dreal import *

# ctx = Context()
# vars = Variables([])
# x = Variable("t")
# y = Variable("yy")
# ctx.DeclareVariable(x)
# ctx.DeclareVariable(y)
# f_sat = logical_and(y > 0, x > 0, forall(vars, logical_and(logical_or(y > 1, y < 10), x < 10, x > 11)))
# print(f_sat)
# ctx.Assert(f_sat)
# result = ctx.CheckSat()
x = Variable("x")
y = Variable("y")
ctx = Context()
ctx.SetLogic(Logic.QF_NRA)
var = Variables()
ctx.DeclareVariable(x, -10, 10)
ctx.DeclareVariable(y, -10, 10)
ctx.Assert(And(x > 0, forall(var, Formula.TRUE())))
result = ctx.CheckSat()



'''
<Formula "(invAtomicID_0_0 and invAtomicID_3_0 and invAtomicID_4_0 and invAtomicID_0_1 and invAtomicID_3_1 and invAtomicID_4_1 and invAtomicID_0_2 and invAtomicID_3_2 and 
invAtomicID_4_2 and invAtomicID_5_0 and invAtomicID_5_1 and invAtomicID_5_2 
and (invAtomicID_0_0 or !(forall({x}. (x > -10)))) 
and (invAtomicID_1_0 or invAtomicID_2_0) 
and (invAtomicID_1_0 or !(forall({x}. (x > -15)))) 
and (invAtomicID_2_0 or !(forall({x}. (x < 20)))) 
and (invAtomicID_3_0 or !(forall({x}. (x > 0)))) 
and (invAtomicID_4_0 or !(forall({x}. (x < 50)))) 
and (invAtomicID_0_1 or !(forall({x}. (x > -10)))) 
and (invAtomicID_1_1 or invAtomicID_2_1) 
and (invAtomicID_1_1 or !(forall({x}. (x > -15)))) 
and (invAtomicID_2_1 or !(forall({x}. (x < 20)))) 
and (invAtomicID_3_1 or !(forall({x}. (x > 0)))) 
and (invAtomicID_4_1 or !(forall({x}. (x < 50)))) 
and (invAtomicID_0_2 or !(forall({x}. (x > -10)))) 
and (invAtomicID_1_2 or invAtomicID_2_2) 
and (invAtomicID_1_2 or !(forall({x}. (x > -15)))) 
and (invAtomicID_2_2 or !(forall({x}. (x < 20)))) 
and (invAtomicID_3_2 or !(forall({x}. (x > 0)))) 
and (invAtomicID_4_2 or !(forall({x}. (x < 50)))) 
and (invAtomicID_5_0 or !(forall({x}. (x <= 30)))) 
and (invAtomicID_5_1 or !(forall({x}. (x <= 30)))) 
and (invAtomicID_5_2 or !(forall({x}. (x <= 30)))) 
and (!(invAtomicID_0_0) or forall({x}. (x > -10))) 
and (!(invAtomicID_1_0) or forall({x}. (x > -15))) 
and (!(invAtomicID_2_0) or forall({x}. (x < 20))) 
and (!(invAtomicID_3_0) or forall({x}. (x > 0))) 
and (!(invAtomicID_4_0) or forall({x}. (x < 50))) 
and (!(invAtomicID_0_1) or forall({x}. (x > -10))) 
and (!(invAtomicID_1_1) or forall({x}. (x > -15))) 
and (!(invAtomicID_2_1) or forall({x}. (x < 20))) 
and (!(invAtomicID_3_1) or forall({x}. (x > 0))) 
and (!(invAtomicID_4_1) or forall({x}. (x < 50))) 
and (!(invAtomicID_0_2) or forall({x}. (x > -10))) 
and (!(invAtomicID_1_2) or forall({x}. (x > -15))) 
and (!(invAtomicID_2_2) or forall({x}. (x < 20))) 
and (!(invAtomicID_3_2) or forall({x}. (x > 0))) 
and (!(invAtomicID_4_2) or forall({x}. (x < 50))) 
and (!(invAtomicID_5_0) or forall({x}. (x <= 30))) 
and (!(invAtomicID_5_1) or forall({x}. (x <= 30))) 
and (!(invAtomicID_5_2) or forall({x}. (x <= 30))))">

'''
#result = CheckSatisfiability(f_sat, 0.001)
print(result)
