[build-system]
requires = ["scikit-build-core"]
build-backend = "scikit_build_core.build"

[project]
name = "stlmc"
version = "1.0.1.dev3"
description = "An SMT-based bounded model checker for signal temporal logic"
readme = "README.md"
license.text = "GPLv3"
keywords = ["stlmc", "model checker", "STL", "signal temporal logic", "bounded model checker"]
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
	  "Topic :: Scientific/Engineering",
    "Operating System :: OS Independent",
]
dependencies = [
  "yices",
  "z3-solver==4.13.2.0",
  "antlr4-python3-runtime==4.13.2",
  "sympy",
  "numpy",
  "bokeh==3.1.1",
  "scipy"
]

[[project.authors]]
name  = "Geunyeol Yu"
email = "rgyen@postech.ac.kr"

[project.scripts]
stlmc = "stlmc.cli.mc:main"
stlmc-vis = "stlmc.cli.visualize:main"
stlmc-install-solvers = "stlmc.cli.install_solvers:main"

[project.urls]
"Homepage"      = "https://stlmc.github.io/"
"Bug Tracker"   = "https://github.com/stlmc/stlmc/issues"
"Documentation" = "https://stlmc.github.io/assets/files/stlmc-manual.pdf"
"Source Code"   = "https://github.com/stlmc/stlmc/"

[tool.scikit-build]
sdist.include = ["src/"]
sdist.exclude = ["tests/**", "3rd_party/antlr4/**"]
wheel.cmake = false
wheel.platlib = false
wheel.py-api = "py3"
