[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "stlmc"
version = "1.0.1.dev3"
description = "An SMT-based bounded model checker for signal temporal logic"
readme = "README.md"
license.text = "GPLv3"
keywords = ["stlmc", "model checker", "STL", "signal temporal logic", "bounded model checker"]
requires-python = ">=3.8,<3.15"
classifiers = [
    "Programming Language :: Python :: 3",
	  "Programming Language :: Python :: 3.8",
	  "Programming Language :: Python :: 3.9",
	  "Programming Language :: Python :: 3.10",
	  "Programming Language :: Python :: 3.11",
	  "Programming Language :: Python :: 3.12",
	  "Programming Language :: Python :: 3.13",
	  "Programming Language :: Python :: 3.14",
	  "Topic :: Scientific/Engineering",
    "Operating System :: OS Independent",
]
dependencies = [
  "yices==1.1.6",
  "cvc5==1.3.4",
  "z3-solver==4.15.4.0",
  "lark==1.3.1",
  "sympy",
  "numpy",
  "bokeh==3.1.1",
  "scipy"
]

[[project.authors]]
name  = "Geunyeol Yu"
email = "rgyen@postech.ac.kr"

[project.scripts]
stlmc = "stlmc.cli.mc:main"
stlmc-vis = "stlmc.cli.visualize:main"
stlmc-install-solvers = "stlmc.cli.install_solvers:main"

[project.urls]
"Homepage"      = "https://stlmc.github.io/"
"Bug Tracker"   = "https://github.com/stlmc/stlmc/issues"
"Documentation" = "https://stlmc.github.io/assets/files/stlmc-manual.pdf"
"Source Code"   = "https://github.com/stlmc/stlmc/"

[tool.setuptools]
package-dir = {"" = "src"}
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
stlmc = ["default.cfg", "parser/grammars/*.lark"]
