#!/usr/bin/python3

#SBATCH --job-name=stlmc
#SBATCH --output=%x.o%j
#SBATCH --error=%x.e%j
#SBATCH --cpus-per-task=2 # 5 cores
#SBATCH --ntasks-per-node=12 # 5 cores

import multiprocessing
import sys
import os

sys.path.append("/home/rgyenr2/workspace/STL")


from stlmcPy.driver.multiprocess_driver import MultiprocessDriverFactory, MultiprocessStlModelChecker, unit_run

pool = multiprocessing.Pool()

if __name__ == '__main__':
    try:
        # default driver factory
        driver_factory = MultiprocessDriverFactory()

        stlmc = MultiprocessStlModelChecker()
        stlmc.create_simulation_env(driver_factory)
        stlmc.run()

        args = stlmc.get_args()
        result = pool.map_async(unit_run, args)

        pool.close()
        pool.join()

    except SystemExit:
        print("System error")
