#!/usr/local/bin/python3
from stlmcPy.driver.driver import Driver

if __name__ == '__main__':

    try:
        driver = Driver()
        # driver.parse()
        hehe = driver.run("./stlmcPy/tests/benchmark_models/linear/railroadLinearSimplify.model", True)
        # print(hehe)
    except SystemExit:
        print("System error")
