from z3 import *

s = Solver()
a = Real('a')
b = Real('b')
c = Real('c')
d = Real('d')
t = Real('t')
s.add(t >= 0)
s.add(t < 60)
s.add(a < 21.1)
s.add(a > 19.9)
s.add(b == 0.07 * t * t * t + 0.4 * t * t + 0.1 * a)
s.add(c == b)
s.add(d == 0.05 * c * c + 0.02 * t * t )
s.add(b > 0)
s.add(b < 100)
s.add(d > 0)
s.add(d< 100)
s.add(c > 0)
s.add(c < 100)
print(s.check())
